data:
  data_csv_dir: "./dataset/count_number.csv"

train:
  n_train: 10
  pre_trained_model: "vinai/PhoWhisper-tiny" #"vinai/PhoWhisper-tiny"
  epoch_num: 80
  train_batch_size: 24
  test_batch_size: 24
  lr: 0.00005
  checkpoint_dir: "./exp/models/best"
  best_checkpoint:
    data_name: "test"
    metric_type: "accuracy"
  early_stopping:
    patience: 10
    data_name: "test"
    loss_type: "loss"
  best_score: 0
  seed_best: 0

service:
  checkpoint_dir: "./exp/models/best"
