data:
  raw_data_dir: "./dataset/raw_data/audio/"
  raw_data_csv: "./dataset/raw_data/csv_data.csv"

  train_data_dir: "./dataset/train_data/audio/"
  train_data_csv: "./dataset/train_data/csv_data.csv"

  test_data_dir: "./dataset/test_data/audio/"
  test_data_csv: "./dataset/test_data/csv_data.csv"

  train_aug_dir: "./dataset/train_aug/audio/"
  train_aug_csv: "./dataset/train_aug/csv_data.csv"

  vocab_dir: './dataset/vocab_dataset.json'

augment:
  change_speech: [0.8, 1.5]
  change_pitch: [-0.5, 1]
  change_volume: [0.2, 4]

train:
  n_train: 10
  pre_trained_model: "vinai/PhoWhisper-tiny" #"vinai/PhoWhisper-tiny"
  epoch_num: 30
  train_batch_size: 32
  test_batch_size: 32
  lr: 0.00002
  checkpoint_dir: "./exp/models/best"
  best_checkpoint:
    data_name: "test"
    metric_type: "accuracy"
  early_stopping:
    patience: 5
    data_name: "test"
    loss_type: "loss"
  best_score: 0
  best_seed: 0

service:
  checkpoint_dir: "./exp/models/best"