data:
  data_csv_dir: "./dataset/speech_data.csv"
  data_audio_dir: "./dataset/audio"
  data_augment_dir: "./dataset/augment"
  data_augment_csv: "./dataset/augment_data.csv"

augment:
  change_speech: [0.8, 1.5]
  change_pitch: [-0.5, 1]
  change_volume: [0.2, 4]

train:
  n_train: 10
  pre_trained_model: "vinai/PhoWhisper-tiny" #"vinai/PhoWhisper-tiny"
  epoch_num: 30
  train_batch_size: 32
  test_batch_size: 32
  lr: 0.00005
  checkpoint_dir: "./exp/models/best"
  best_checkpoint:
    data_name: "test"
    metric_type: "accuracy"
  early_stopping:
    patience: 10
    data_name: "test"
    loss_type: "loss"
  best_score: 0
  seed_best: 0

service:
  checkpoint_dir: "./exp/models/best"
